DECLARE @CATALOG NVARCHAR(MAX),@SCHEMA NVARCHAR(MAX),@TABLE_NAME NVARCHAR(MAX)
SELECT @CATALOG='TPC-H',@SCHEMA='dbo'

SELECT SPECIFIC_SCHEMA,SPECIFIC_NAME,ROUTINE_DEFINITION
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE='PROCEDURE'--AND SPECIFIC_CATALOG=@CATALOG AND SPECIFIC_SCHEMA=@SCHEMA
ORDER BY SPECIFIC_SCHEMA,SPECIFIC_NAME

SELECT S.name SPECIFIC_SCHEMA,P.name SPECIFIC_NAME,SQL.definition ROUTINE_DEFINITION
FROM sys.procedures P
JOIN sys.all_sql_modules SQL ON P.object_id= SQL.object_id
JOIN sys.schemas S ON P.schema_id=S.schema_id
--WHERE S.name=@TABLE_SCHEMA
ORDER BY S.name,P.name
