DECLARE @SCHEMA NVARCHAR(MAX)
SELECT @SCHEMA='dbo'

--USE [TPC-H] 
SELECT TABLE_SCHEMA,TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE='BASE TABLE'--AND TABLE_SCHEMA=@SCHEMA
ORDER BY TABLE_SCHEMA,TABLE_NAME
