DECLARE @CATALOG NVARCHAR(MAX),@SCHEMA NVARCHAR(MAX),@TABLE_NAME NVARCHAR(MAX)
SELECT @CATALOG='TPC-H',@SCHEMA='dbo',@TABLE_NAME='CUSTOMER'

USE [TPC-H]
SELECT C.DATA_TYPE,KCU.COLUMN_NAME,TC.CONSTRAINT_CATALOG,TC.CONSTRAINT_SCHEMA,TC.TABLE_NAME,KCU.ORDINAL_POSITION
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU ON TC .CONSTRAINT_CATALOG=CCU.CONSTRAINT_CATALOG AND TC .CONSTRAINT_SCHEMA=CCU.CONSTRAINT_SCHEMA AND TC .TABLE_NAME=CCU.TABLE_NAME AND TC .CONSTRAINT_NAME=CCU.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        KCU ON CCU.CONSTRAINT_CATALOG=KCU.CONSTRAINT_CATALOG AND CCU.CONSTRAINT_SCHEMA=KCU.CONSTRAINT_SCHEMA AND CCU.TABLE_NAME=KCU.TABLE_NAME AND CCU.CONSTRAINT_NAME=KCU.CONSTRAINT_NAME AND CCU.COLUMN_NAME=KCU.COLUMN_NAME
JOIN INFORMATION_SCHEMA.COLUMNS                 C   ON KCU.CONSTRAINT_CATALOG=C  .TABLE_CATALOG      AND KCU.CONSTRAINT_SCHEMA=C  .TABLE_SCHEMA      AND KCU.TABLE_NAME=C  .TABLE_NAME AND KCU.COLUMN_NAME    =C  .COLUMN_NAME
WHERE TC.CONSTRAINT_TYPE='PRIMARY KEY' --AND TC.CONSTRAINT_CATALOG=@CATALOG AND TC.CONSTRAINT_SCHEMA=@SCHEMA AND TC.TABLE_NAME=@TABLE_NAME
ORDER BY TC.CONSTRAINT_CATALOG,TC.CONSTRAINT_SCHEMA,TC.TABLE_NAME,KCU.ORDINAL_POSITION


--SELECT CASE WHEN PRIMARY_KEY.ORDINAL_POSITION IS NULL THEN''ELSE'True'END,COLUMNS.DATA_TYPE,COLUMNS.COLUMN_NAME,COLUMNS.IS_NULLABLE
--FROM INFORMATION_SCHEMA.COLUMNS COLUMNS
--LEFT JOIN(
--	SELECT C.DATA_TYPE,KCU.COLUMN_NAME,TC.CONSTRAINT_CATALOG,TC.CONSTRAINT_SCHEMA,TC.TABLE_NAME,KCU.ORDINAL_POSITION
--	FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
--	JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU ON TC .CONSTRAINT_CATALOG=CCU.CONSTRAINT_CATALOG AND TC .CONSTRAINT_SCHEMA=CCU.CONSTRAINT_SCHEMA AND TC .TABLE_NAME=CCU.TABLE_NAME AND TC .CONSTRAINT_NAME=CCU.CONSTRAINT_NAME
--	JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        KCU ON CCU.CONSTRAINT_CATALOG=KCU.CONSTRAINT_CATALOG AND CCU.CONSTRAINT_SCHEMA=KCU.CONSTRAINT_SCHEMA AND CCU.TABLE_NAME=KCU.TABLE_NAME AND CCU.CONSTRAINT_NAME=KCU.CONSTRAINT_NAME AND CCU.COLUMN_NAME=KCU.COLUMN_NAME
--	JOIN INFORMATION_SCHEMA.COLUMNS                 C   ON KCU.CONSTRAINT_CATALOG=C  .TABLE_CATALOG      AND KCU.CONSTRAINT_SCHEMA=C  .TABLE_SCHEMA      AND KCU.TABLE_NAME=C  .TABLE_NAME AND KCU.COLUMN_NAME    =C  .COLUMN_NAME
--	WHERE TC.CONSTRAINT_TYPE='PRIMARY KEY' AND TC.CONSTRAINT_CATALOG=@CATALOG AND TC.CONSTRAINT_SCHEMA=@SCHEMA AND TC.TABLE_NAME=@TABLE_NAME
--)PRIMARY_KEY ON COLUMNS.COLUMN_NAME=PRIMARY_KEY.COLUMN_NAME
--WHERE COLUMNS.TABLE_CATALOG=@CATALOG AND COLUMNS.TABLE_SCHEMA=@SCHEMA AND COLUMNS.TABLE_NAME=@TABLE_NAME
--ORDER BY COLUMNS.ORDINAL_POSITION


--SELECT C.DATA_TYPE,KCU.COLUMN_NAME,TC.CONSTRAINT_CATALOG,TC.CONSTRAINT_SCHEMA,TC.TABLE_NAME,KCU.ORDINAL_POSITION
--FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
--JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU ON TC .CONSTRAINT_CATALOG=CCU.CONSTRAINT_CATALOG AND TC .CONSTRAINT_SCHEMA=CCU.CONSTRAINT_SCHEMA AND TC .TABLE_NAME=CCU.TABLE_NAME AND TC .CONSTRAINT_NAME=CCU.CONSTRAINT_NAME
--JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        KCU ON CCU.CONSTRAINT_CATALOG=KCU.CONSTRAINT_CATALOG AND CCU.CONSTRAINT_SCHEMA=KCU.CONSTRAINT_SCHEMA AND CCU.TABLE_NAME=KCU.TABLE_NAME AND CCU.CONSTRAINT_NAME=KCU.CONSTRAINT_NAME AND CCU.COLUMN_NAME=KCU.COLUMN_NAME
--JOIN INFORMATION_SCHEMA.COLUMNS                 C   ON KCU.CONSTRAINT_CATALOG=C  .TABLE_CATALOG      AND KCU.CONSTRAINT_SCHEMA=C  .TABLE_SCHEMA      AND KCU.TABLE_NAME=C  .TABLE_NAME AND KCU.COLUMN_NAME    =C  .COLUMN_NAME
--WHERE TC.CONSTRAINT_TYPE='PRIMARY KEY' AND TC.CONSTRAINT_CATALOG=@CATALOG AND TC.CONSTRAINT_SCHEMA=@SCHEMA AND TC.TABLE_NAME=@TABLE_NAME
----ORDER BY TC.CONSTRAINT_CATALOG,TC.CONSTRAINT_SCHEMA,TC.TABLE_NAME,KCU.ORDINAL_POSITION

