SELECT 
     TC_N.CONSTRAINT_NAME   外部キー
    ,TC_N.TABLE_SCHEMA      子スキーマ
    ,TC_N.TABLE_NAME        子テーブル
    ,KCU_N.COLUMN_NAME      子列
    ,KCU_N.ORDINAL_POSITION 子列順序
    ,TC_1.TABLE_SCHEMA
    ,TC_1.TABLE_NAME
    --,TC_1.TABLE_SCHEMA      スキーマ
    --,TC_1.TABLE_NAME        テーブル
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS       TC_N 
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        KCU_N ON TC_N .CONSTRAINT_CATALOG=KCU_N.CONSTRAINT_CATALOG AND TC_N .CONSTRAINT_SCHEMA=KCU_N.CONSTRAINT_SCHEMA AND TC_N .CONSTRAINT_NAME=KCU_N.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC_N  ON KCU_N.CONSTRAINT_CATALOG=RC_N .CONSTRAINT_CATALOG AND KCU_N.CONSTRAINT_SCHEMA=RC_N .CONSTRAINT_SCHEMA AND KCU_N.CONSTRAINT_NAME=RC_N .CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS       TC_1  ON RC_N .UNIQUE_CONSTRAINT_CATALOG=TC_1 .CONSTRAINT_CATALOG AND RC_N .UNIQUE_CONSTRAINT_SCHEMA=TC_1 .CONSTRAINT_SCHEMA AND RC_N .UNIQUE_CONSTRAINT_NAME=TC_1 .CONSTRAINT_NAME
WHERE TC_N.CONSTRAINT_TYPE='FOREIGN KEY'
--AND TC_1.TABLE_SCHEMA=@TABLE_SCHEMA         AND TC_1.TABLE_NAME=@TABLE_NAME        --自身
--AND TC_N.TABLE_SCHEMA=@FOREIGN_TABLE_SCHEMA AND TC_N.TABLE_NAME=@FOREIGN_TABLE_NAME--子
ORDER BY
     TC_N.CONSTRAINT_NAME
    ,TC_N.TABLE_SCHEMA
    ,TC_N.TABLE_NAME
    ,KCU_N.ORDINAL_POSITION
