SELECT
	 一列.TABLE_NAME
	,一列.COLUMN_NAME
	,多列.TABLE_NAME
	,多列.COLUMN_NAME
    ,多表.CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS       多表
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        多列 ON 多表.CONSTRAINT_CATALOG       =多列.CONSTRAINT_CATALOG AND 多表.CONSTRAINT_SCHEMA       =多列.CONSTRAINT_SCHEMA AND 多表.CONSTRAINT_NAME       =多列.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 参照 ON 多列.CONSTRAINT_CATALOG       =参照.CONSTRAINT_CATALOG AND 多列.CONSTRAINT_SCHEMA       =参照.CONSTRAINT_SCHEMA AND 多列.CONSTRAINT_NAME       =参照.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS       一表 ON 参照.UNIQUE_CONSTRAINT_CATALOG=一表.CONSTRAINT_CATALOG AND 参照.UNIQUE_CONSTRAINT_SCHEMA=一表.CONSTRAINT_SCHEMA AND 参照.UNIQUE_CONSTRAINT_NAME=一表.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        一列 ON 一表.CONSTRAINT_CATALOG       =一列.CONSTRAINT_CATALOG AND 一表.CONSTRAINT_SCHEMA       =一列.CONSTRAINT_SCHEMA AND 一表.CONSTRAINT_NAME       =一列.CONSTRAINT_NAME AND 多列.ORDINAL_POSITION=一列.ORDINAL_POSITION
JOIN INFORMATION_SCHEMA.COLUMNS                 順序 ON 一列.TABLE_CATALOG            =順序.TABLE_CATALOG      AND 一列.TABLE_SCHEMA            =順序.TABLE_SCHEMA      AND 一列.TABLE_NAME            =順序.TABLE_NAME      AND 一列.COLUMN_NAME     =順序.COLUMN_NAME
ORDER BY
     一表.TABLE_SCHEMA
    ,一表.TABLE_NAME
    ,多表.TABLE_SCHEMA
    ,多表.TABLE_NAME
    ,順序.ORDINAL_POSITION


DECLARE @TABLE_SCHEMA NVARCHAR(MAX),@TABLE_NAME NVARCHAR(MAX),@FOREIGN_TABLE_SCHEMA NVARCHAR(MAX),@FOREIGN_TABLE_NAME NVARCHAR(MAX)
--自身
SELECT @TABLE_SCHEMA='dbo',@TABLE_NAME='LINEITEM'
--親
SELECT @FOREIGN_TABLE_SCHEMA='dbo',@FOREIGN_TABLE_NAME='PARTSUPP'
--SELECT @CATALOG='TPC-H',@TABLE_SCHEMA='dbo',@TABLE_NAME='CUSTOMER',@FOREIGN_TABLE_SCHEMA='dbo',@FOREIGN_TABLE_NAME='NATION'


SELECT 
     多列.COLUMN_NAME       子列
    ,多表.CONSTRAINT_NAME   外部キー
    ,一表.TABLE_NAME        親テーブル
    ,多表.TABLE_NAME        子テーブル
    ,多列.ORDINAL_POSITION 列順序
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 多表 
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE 多列 
        ON 多表.CONSTRAINT_CATALOG=多列.CONSTRAINT_CATALOG 
    AND 多表.CONSTRAINT_SCHEMA=多列.CONSTRAINT_SCHEMA 
    AND 多表.CONSTRAINT_NAME=多列.CONSTRAINT_NAME 
INNER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC_N 
        ON 多列.CONSTRAINT_CATALOG=RC_N.CONSTRAINT_CATALOG 
    AND 多列.CONSTRAINT_SCHEMA=RC_N.CONSTRAINT_SCHEMA 
    AND 多列.CONSTRAINT_NAME=RC_N.CONSTRAINT_NAME 
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS 一表 
        ON RC_N.UNIQUE_CONSTRAINT_CATALOG=一表.CONSTRAINT_CATALOG 
    AND RC_N.UNIQUE_CONSTRAINT_SCHEMA=一表.CONSTRAINT_SCHEMA 
    AND RC_N.UNIQUE_CONSTRAINT_NAME=一表.CONSTRAINT_NAME 
INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU_1 
        ON 一表.CONSTRAINT_CATALOG=CCU_1.CONSTRAINT_CATALOG 
    AND 一表.CONSTRAINT_SCHEMA=CCU_1.CONSTRAINT_SCHEMA 
    AND 一表.CONSTRAINT_NAME=CCU_1.CONSTRAINT_NAME 
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE 一列 
        ON CCU_1.CONSTRAINT_CATALOG=一列.CONSTRAINT_CATALOG 
    AND CCU_1.CONSTRAINT_SCHEMA=一列.CONSTRAINT_SCHEMA 
    AND CCU_1.CONSTRAINT_NAME=一列.CONSTRAINT_NAME 
    AND CCU_1.COLUMN_NAME=一列.COLUMN_NAME 
    AND 多列.ORDINAL_POSITION=一列.ORDINAL_POSITION 
WHERE 多表.CONSTRAINT_TYPE='FOREIGN KEY'
--AND 多表.TABLE_SCHEMA=@TABLE_SCHEMA         AND 多表.TABLE_NAME=@TABLE_NAME        --自身
--AND 一表.TABLE_SCHEMA=@FOREIGN_TABLE_SCHEMA AND 一表.TABLE_NAME=@FOREIGN_TABLE_NAME--親
ORDER BY
     多表.CONSTRAINT_NAME
    ,一表.TABLE_NAME
    ,多表.TABLE_NAME
    ,多列.ORDINAL_POSITION
    -- 多表.TABLE_NAME
    --,一表.TABLE_NAME
    --,多列.ORDINAL_POSITION

SELECT 
     一表.CONSTRAINT_NAME  親外部キー
    ,一表.TABLE_NAME       親テーブル
    ,一列.COLUMN_NAME      親列
    ,多表.CONSTRAINT_NAME  子外部キー
    ,多表.TABLE_NAME       子テーブル
    ,多列.COLUMN_NAME      子列
    ,多列.ORDINAL_POSITION 列順序
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 多表
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE 多制約 
     ON 多表.CONSTRAINT_CATALOG       =多制約.CONSTRAINT_CATALOG 
    AND 多表.CONSTRAINT_SCHEMA        =多制約.CONSTRAINT_SCHEMA 
    AND 多表.CONSTRAINT_NAME          =多制約.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE 多列 
     ON 多表.CONSTRAINT_CATALOG       =多列.CONSTRAINT_CATALOG 
    AND 多表.CONSTRAINT_SCHEMA        =多列.CONSTRAINT_SCHEMA 
    AND 多表.CONSTRAINT_NAME          =多列.CONSTRAINT_NAME 
    AND 多制約.COLUMN_NAME            =多列.COLUMN_NAME 
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 参照 
     ON 多列.CONSTRAINT_CATALOG       =参照.CONSTRAINT_CATALOG 
    AND 多列.CONSTRAINT_SCHEMA        =参照.CONSTRAINT_SCHEMA 
    AND 多列.CONSTRAINT_NAME          =参照.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS 一表 
     ON 参照.UNIQUE_CONSTRAINT_CATALOG=一表.CONSTRAINT_CATALOG 
    AND 参照.UNIQUE_CONSTRAINT_SCHEMA =一表.CONSTRAINT_SCHEMA 
    AND 参照.UNIQUE_CONSTRAINT_NAME   =一表.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE 一制約 
     ON 一表.CONSTRAINT_CATALOG       =一制約.CONSTRAINT_CATALOG 
    AND 一表.CONSTRAINT_SCHEMA        =一制約.CONSTRAINT_SCHEMA 
    AND 一表.CONSTRAINT_NAME          =一制約.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE 一列 
     ON 多列.CONSTRAINT_CATALOG       =一列.CONSTRAINT_CATALOG 
    AND 多列.CONSTRAINT_SCHEMA        =一列.CONSTRAINT_SCHEMA 
    AND 多列.CONSTRAINT_NAME          =一列.CONSTRAINT_NAME 
    AND 一制約.COLUMN_NAME            =一列.COLUMN_NAME 
    --AND 多列.ORDINAL_POSITION         =一列.ORDINAL_POSITION 
--WHERE 多表.CONSTRAINT_TYPE='FOREIGN KEY'
ORDER BY
     多表.CONSTRAINT_NAME
    ,一表.TABLE_NAME
    ,多表.TABLE_NAME
    ,多列.ORDINAL_POSITION


SELECT
     一表.CONSTRAINT_NAME  親外部キー
	,一列.TABLE_NAME       親表
	,一列.COLUMN_NAME      親列
    ,多表.CONSTRAINT_NAME  子外部キー
	,多列.TABLE_NAME       子表
	,多列.COLUMN_NAME      子列
    ,多列.ORDINAL_POSITION 列順序
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 多表
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE 多列 
     ON 多表.CONSTRAINT_CATALOG       =多列.CONSTRAINT_CATALOG 
    AND 多表.CONSTRAINT_SCHEMA        =多列.CONSTRAINT_SCHEMA 
    AND 多表.CONSTRAINT_NAME          =多列.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 参照 
     ON 多列.CONSTRAINT_CATALOG       =参照.CONSTRAINT_CATALOG 
    AND 多列.CONSTRAINT_SCHEMA        =参照.CONSTRAINT_SCHEMA 
    AND 多列.CONSTRAINT_NAME          =参照.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS 一表
     ON 参照.UNIQUE_CONSTRAINT_CATALOG=一表.CONSTRAINT_CATALOG 
    AND 参照.UNIQUE_CONSTRAINT_SCHEMA =一表.CONSTRAINT_SCHEMA 
    AND 参照.UNIQUE_CONSTRAINT_NAME   =一表.CONSTRAINT_NAME 
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE 一列 
     ON 一表.CONSTRAINT_CATALOG       =一列.CONSTRAINT_CATALOG 
    AND 一表.CONSTRAINT_SCHEMA        =一列.CONSTRAINT_SCHEMA 
    AND 一表.CONSTRAINT_NAME          =一列.CONSTRAINT_NAME 
    AND 多列.ORDINAL_POSITION         =一列.ORDINAL_POSITION
    --AND 多列.ORDINAL_POSITION         =一列.ORDINAL_POSITION 
--WHERE 多表.CONSTRAINT_TYPE='FOREIGN KEY'
ORDER BY
     多表.CONSTRAINT_NAME
    ,一表.TABLE_NAME
    ,多表.TABLE_NAME
    ,多列.ORDINAL_POSITION
