--USE [msdb] 
SELECT 
     TC_1.TABLE_SCHEMA
    ,TC_1.TABLE_NAME
    ,TC_N.TABLE_SCHEMA
    ,TC_N.TABLE_NAME
    ,TC_N.CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS       TC_N
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        KCU_N ON TC_N .CONSTRAINT_CATALOG       =KCU_N.CONSTRAINT_CATALOG AND TC_N .CONSTRAINT_SCHEMA       =KCU_N.CONSTRAINT_SCHEMA AND TC_N .CONSTRAINT_NAME       =KCU_N.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC_N  ON KCU_N.CONSTRAINT_CATALOG       =RC_N .CONSTRAINT_CATALOG AND KCU_N.CONSTRAINT_SCHEMA       =RC_N .CONSTRAINT_SCHEMA AND KCU_N.CONSTRAINT_NAME       =RC_N .CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS       TC_1  ON RC_N .UNIQUE_CONSTRAINT_CATALOG=TC_1 .CONSTRAINT_CATALOG AND RC_N .UNIQUE_CONSTRAINT_SCHEMA=TC_1 .CONSTRAINT_SCHEMA AND RC_N .UNIQUE_CONSTRAINT_NAME=TC_1 .CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU_1 ON TC_1 .CONSTRAINT_CATALOG       =CCU_1.CONSTRAINT_CATALOG AND TC_1 .CONSTRAINT_SCHEMA       =CCU_1.CONSTRAINT_SCHEMA AND TC_1 .CONSTRAINT_NAME       =CCU_1.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        KCU_1 ON CCU_1.CONSTRAINT_CATALOG       =KCU_1.CONSTRAINT_CATALOG AND CCU_1.CONSTRAINT_SCHEMA       =KCU_1.CONSTRAINT_SCHEMA AND CCU_1.CONSTRAINT_NAME       =KCU_1.CONSTRAINT_NAME --AND CCU_1.COLUMN_NAME=KCU_1.COLUMN_NAME --AND KCU_N.ORDINAL_POSITION=KCU_1.ORDINAL_POSITION
WHERE TC_N.CONSTRAINT_TYPE='FOREIGN KEY'
--AND TC_N.TABLE_SCHEMA=@TABLE_SCHEMA AND TC_N.TABLE_NAME=@TABLE_NAME
ORDER BY 
     TC_1.TABLE_SCHEMA
    ,TC_1.TABLE_NAME
    ,TC_N.TABLE_SCHEMA
    ,TC_N.TABLE_NAME
