//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqDB.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}バイト受信した。{1}バイト受信できなかった。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _バイト受信した_バイト受信できなかった {
            get {
                return ResourceManager.GetString("_バイト受信した_バイト受信できなかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DynamicMethodでFaultはサポートされていない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DynamicMethodでFaultはサポートされていない {
            get {
                return ResourceManager.GetString("DynamicMethodでFaultはサポートされていない", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DynamicMethodでFilterはサポートされていない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DynamicMethodでFilterはサポートされていない {
            get {
                return ResourceManager.GetString("DynamicMethodでFilterはサポートされていない", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クライアントでChainStatusが空でない配列を返した。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string クライアントでChainStatusが空でない配列を返した {
            get {
                return ResourceManager.GetString("クライアントでChainStatusが空でない配列を返した", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クライアントでサーバー証明書の検証に成功した。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string クライアントでサーバー証明書の検証に成功しなかった {
            get {
                return ResourceManager.GetString("クライアントでサーバー証明書の検証に成功しなかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クライアントで証明書が利用できない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string クライアントで証明書が利用できなかった {
            get {
                return ResourceManager.GetString("クライアントで証明書が利用できなかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クライアントで証明書名が不一致だった。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string クライアントで証明書名が不一致だった {
            get {
                return ResourceManager.GetString("クライアントで証明書名が不一致だった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーでChainStatusが空でない配列を返した。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string サーバーでChainStatusが空でない配列を返した {
            get {
                return ResourceManager.GetString("サーバーでChainStatusが空でない配列を返した", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーでサーバー証明書の検証に成功した。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string サーバーでサーバー証明書の検証に成功した {
            get {
                return ResourceManager.GetString("サーバーでサーバー証明書の検証に成功した", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーで証明書が利用できなかった。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string サーバーで証明書が利用できなかった {
            get {
                return ResourceManager.GetString("サーバーで証明書が利用できなかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーで証明書名が不一致だった。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string サーバーで証明書名が不一致だった {
            get {
                return ResourceManager.GetString("サーバーで証明書名が不一致だった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキーマとテーブルが発見できなかった。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string スキーマとテーブルが発見できなかった {
            get {
                return ResourceManager.GetString("スキーマとテーブルが発見できなかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ長が読み込めなかった。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string データ長が読み込めなかった {
            get {
                return ResourceManager.GetString("データ長が読み込めなかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トランザクション数が{0}を超えた。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string トランザクション数が_を超えた {
            get {
                return ResourceManager.GetString("トランザクション数が_を超えた", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トランザクション数が1のときCommit出来ない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string トランザクション数が1のときCommit出来なかった {
            get {
                return ResourceManager.GetString("トランザクション数が1のときCommit出来なかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トランザクション数が1未満のときRollback出来ない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string トランザクション数が1未満のときRollback出来なかった {
            get {
                return ResourceManager.GetString("トランザクション数が1未満のときRollback出来なかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハッシュ値が一致しなかった。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ハッシュ値が一致しなかった {
            get {
                return ResourceManager.GetString("ハッシュ値が一致しなかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストID{0},レスポンスID{1}が一致しない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string リクエストID_レスポンスID_が一致しなかった {
            get {
                return ResourceManager.GetString("リクエストID_レスポンスID_が一致しなかった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リモート先から{0}を受信することを期待したが{1}だった。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string リモート先から_を受信することを期待したが_だった {
            get {
                return ResourceManager.GetString("リモート先から_を受信することを期待したが_だった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リモート先で例外が発生した。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string リモート先で例外が発生した {
            get {
                return ResourceManager.GetString("リモート先で例外が発生した", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制約エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 制約エラー {
            get {
                return ResourceManager.GetString("制約エラー", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受信ヘッダー{0}は不正である。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 受信ヘッダー_は不正だった {
            get {
                return ResourceManager.GetString("受信ヘッダー_は不正だった", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自由変数、定数、ラムダ式が多すぎる。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 自由変数定数ラムダ式が多すぎた {
            get {
                return ResourceManager.GetString("自由変数定数ラムダ式が多すぎた", resourceCulture);
            }
        }
    }
}
