WITH 多表 AS(
	SELECT CONSTRAINT_NAME,TABLE_SCHEMA,TABLE_NAME,CONSTRAINT_CATALOG,CONSTRAINT_SCHEMA
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
),多列 AS(
	SELECT COLUMN_NAME,CONSTRAINT_CATALOG,CONSTRAINT_SCHEMA,CONSTRAINT_NAME,ORDINAL_POSITION
    FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
),参照 AS(
	SELECT CONSTRAINT_CATALOG,CONSTRAINT_SCHEMA,CONSTRAINT_NAME,UNIQUE_CONSTRAINT_CATALOG,UNIQUE_CONSTRAINT_SCHEMA,UNIQUE_CONSTRAINT_NAME
    FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
),一表 AS(
	SELECT TABLE_SCHEMA,TABLE_NAME,CONSTRAINT_CATALOG,CONSTRAINT_SCHEMA,CONSTRAINT_NAME
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
),一列 AS(
	SELECT CONSTRAINT_CATALOG,CONSTRAINT_SCHEMA,CONSTRAINT_NAME,ORDINAL_POSITION,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME
    FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
),順序 AS(
	SELECT TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION
	FROM INFORMATION_SCHEMA.COLUMNS
)
SELECT
	 多表.CONSTRAINT_NAME
	,多表.TABLE_SCHEMA
	,多表.TABLE_NAME
	,多列.COLUMN_NAME
	,一表.TABLE_SCHEMA
	,一表.TABLE_NAME
FROM 多表
JOIN 多列 ON 多表.CONSTRAINT_CATALOG       =多列.CONSTRAINT_CATALOG AND 多表.CONSTRAINT_SCHEMA       =多列.CONSTRAINT_SCHEMA AND 多表.CONSTRAINT_NAME       =多列.CONSTRAINT_NAME
JOIN 参照 ON 多列.CONSTRAINT_CATALOG       =参照.CONSTRAINT_CATALOG AND 多列.CONSTRAINT_SCHEMA       =参照.CONSTRAINT_SCHEMA AND 多列.CONSTRAINT_NAME       =参照.CONSTRAINT_NAME
JOIN 一表 ON 参照.UNIQUE_CONSTRAINT_CATALOG=一表.CONSTRAINT_CATALOG AND 参照.UNIQUE_CONSTRAINT_SCHEMA=一表.CONSTRAINT_SCHEMA AND 参照.UNIQUE_CONSTRAINT_NAME=一表.CONSTRAINT_NAME
JOIN 一列 ON 一表.CONSTRAINT_CATALOG       =一列.CONSTRAINT_CATALOG AND 一表.CONSTRAINT_SCHEMA       =一列.CONSTRAINT_SCHEMA AND 一表.CONSTRAINT_NAME       =一列.CONSTRAINT_NAME AND 多列.ORDINAL_POSITION=一列.ORDINAL_POSITION
JOIN INFORMATION_SCHEMA.COLUMNS                 順序 ON 一列.TABLE_CATALOG            =順序.TABLE_CATALOG      AND 一列.TABLE_SCHEMA            =順序.TABLE_SCHEMA      AND 一列.TABLE_NAME            =順序.TABLE_NAME      AND 一列.COLUMN_NAME     =順序.COLUMN_NAME
ORDER BY
	 一表.TABLE_SCHEMA
	,一表.TABLE_NAME
	,多表.TABLE_SCHEMA
	,多表.TABLE_NAME


WITH W AS(
	SELECT 表.CONSTRAINT_NAME 表_CONSTRAINT_NAME
		  ,表.CONSTRAINT_CATALOG 表_CONSTRAINT_CATALOG
		  ,表.CONSTRAINT_SCHEMA 表_CONSTRAINT_SCHEMA
          ,表.TABLE_SCHEMA 表_TABLE_SCHEMA
          ,表.TABLE_NAME 表_TABLE_NAME
		  ,列.TABLE_CATALOG 列_TABLE_CATALOG
		  ,列.TABLE_SCHEMA 列_TABLE_SCHEMA
		  ,列.TABLE_NAME 列_TABLE_NAME
          ,列.COLUMN_NAME 列_COLUMN_NAME
		  ,列.CONSTRAINT_CATALOG 列_CONSTRAINT_CATALOG
		  ,列.CONSTRAINT_SCHEMA 列_CONSTRAINT_SCHEMA
		  ,列.CONSTRAINT_NAME 列_CONSTRAINT_NAME
		  ,列.ORDINAL_POSITION
	FROM
	INFORMATION_SCHEMA.TABLE_CONSTRAINTS     表
	JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE 列 ON 表.CONSTRAINT_CATALOG=列.CONSTRAINT_CATALOG AND 表.CONSTRAINT_SCHEMA=列.CONSTRAINT_SCHEMA AND 表.CONSTRAINT_NAME=列.CONSTRAINT_NAME
)
        SELECT
             多表.CONSTRAINT_NAME
            ,多表.TABLE_SCHEMA
            ,多表.TABLE_NAME
            ,多列.COLUMN_NAME
            ,一表.TABLE_SCHEMA
            ,一表.TABLE_NAME
        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS       多表
        JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        多列 ON 多表.CONSTRAINT_CATALOG       =多列.CONSTRAINT_CATALOG AND 多表.CONSTRAINT_SCHEMA       =多列.CONSTRAINT_SCHEMA AND 多表.CONSTRAINT_NAME       =多列.CONSTRAINT_NAME
        JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 参照 ON 多列.CONSTRAINT_CATALOG       =参照.CONSTRAINT_CATALOG AND 多列.CONSTRAINT_SCHEMA       =参照.CONSTRAINT_SCHEMA AND 多列.CONSTRAINT_NAME       =参照.CONSTRAINT_NAME
        JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS       一表 ON 参照.UNIQUE_CONSTRAINT_CATALOG=一表.CONSTRAINT_CATALOG AND 参照.UNIQUE_CONSTRAINT_SCHEMA=一表.CONSTRAINT_SCHEMA AND 参照.UNIQUE_CONSTRAINT_NAME=一表.CONSTRAINT_NAME
        JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        一列 ON 一表.CONSTRAINT_CATALOG       =一列.CONSTRAINT_CATALOG AND 一表.CONSTRAINT_SCHEMA       =一列.CONSTRAINT_SCHEMA AND 一表.CONSTRAINT_NAME       =一列.CONSTRAINT_NAME AND 多列.ORDINAL_POSITION=一列.ORDINAL_POSITION
        JOIN INFORMATION_SCHEMA.COLUMNS                 順序 ON 一列.TABLE_CATALOG            =順序.TABLE_CATALOG      AND 一列.TABLE_SCHEMA            =順序.TABLE_SCHEMA      AND 一列.TABLE_NAME            =順序.TABLE_NAME      AND 一列.COLUMN_NAME     =順序.COLUMN_NAME
        ORDER BY
             一表.TABLE_SCHEMA
            ,一表.TABLE_NAME
            ,多表.TABLE_SCHEMA
            ,多表.TABLE_NAME
            ,順序.ORDINAL_POSITION;
        