
SELECT C.DATA_TYPE,C.COLUMN_NAME,C.IS_NULLABLE,(
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
    JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC ON KCU.CONSTRAINT_CATALOG=TC.CONSTRAINT_CATALOG AND KCU.CONSTRAINT_SCHEMA=TC.CONSTRAINT_SCHEMA  AND KCU.CONSTRAINT_NAME=TC.CONSTRAINT_NAME AND TC.CONSTRAINT_TYPE='PRIMARY KEY'
    WHERE C.TABLE_CATALOG=KCU.CONSTRAINT_CATALOG AND C.TABLE_SCHEMA=KCU.CONSTRAINT_SCHEMA AND C.TABLE_NAME=KCU.TABLE_NAME AND C.COLUMN_NAME=KCU.COLUMN_NAME
)IsPrimaryKey
FROM INFORMATION_SCHEMA.COLUMNS C
--WHERE C.TABLE_CATALOG=@CATALOG AND C.TABLE_SCHEMA=@SCHEMA AND C.TABLE_NAME=@NAME
ORDER BY C.TABLE_CATALOG,C.TABLE_SCHEMA,C.TABLE_NAME,C.ORDINAL_POSITION
    