DECLARE @CATALOG NVARCHAR(MAX),@SCHEMA NVARCHAR(MAX),@TABLE_NAME NVARCHAR(MAX)
SELECT @CATALOG='TPC-H',@SCHEMA='dbo'
USE [TPC-H] 
SELECT SPECIFIC_NAME,ROUTINE_DEFINITION
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE='PROCEDURE'AND SPECIFIC_CATALOG=@CATALOG AND SPECIFIC_SCHEMA=@SCHEMA

